version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@storybook/react"
    versions:
    - ">= 6.0.a, < 6.1"
  - dependency-name: ts-loader
    versions:
    - 9.1.0
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.19
    - 6.2.5
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.19
    - 6.2.1
    - 6.2.2
    - 6.2.5
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.16
    - 6.1.19
    - 6.2.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
